apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedCiliumNetworkPolicy
description: "L7 policy to restrict access to specific HTTP call"
metadata:
  name: "rule1"
spec:
  template:
    spec:
      endpointSelector:
        matchLabels:
          org: empire
          class: deathstar
      ingress:
      - fromEndpoints:
        - matchLabels:
            org: empire
        toPorts:
        - ports:
          - port: "80"
            protocol: TCP
          rules:
            http:
            - method: "POST"
              path: "/v1/request-landing"
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedCiliumNetworkPolicyPlacement
metadata:
  name: "rule1"
spec:
  clusterNames:
  - cluster2
  - cluster1
